# Generated by Django 5.0.6 on 2024-06-25 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=200)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navs', to='role.role')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(default='<i className="fa fa-circle-o"></i>', max_length=200)),
                ('content', models.TextField()),
                ('nav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='role.nav')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_child', to='role.role')),
            ],
        ),
    ]
