# Generated by Django 5.0.6 on 2024-06-25 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.contrib.auth import get_user_model
import random
import string


def create_superuser(apps, schema_editor):
    User = get_user_model()
    # Superuser uchun login va parolni aniqlaymiz
    username = 'admin'
    password = ''.join(random.choices(string.ascii_letters + string.digits, k=12))
    email = 'admin@example.com'

    # Superuser yaratamiz
    User.objects.create_superuser(username=username, email=email, password=password)

    # Parolni faylga yozamiz
    with open('password.txt', 'w') as f:
        f.write(f'Username: {username}\n')
        f.write(f'Password: {password}\n')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=200)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navs', to='role.role')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(default='<i className="fa fa-circle-o"></i>', max_length=200)),
                ('content', models.TextField()),
                ('nav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='role.nav')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_child', to='role.role')),
            ],
        ),
        migrations.RunPython(create_superuser),
    ]
